name: Deploy to server
on:
  workflow_call:
jobs:
  connect-to-server:
    runs-on: ubuntu-latest
    env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_TAG: ${{ github.sha }}

    steps:
      - name: checkout code
        uses : actions/checkout@v4

      - name: secure ssh to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          script: |
            echo "updating the server"
            sudo apt-get update && apt-get install docker.io docker-compose-v2 -y
            sudo usermod -aG docker $USER
            sudo systemctl start docker
            sudo systemctl enable docker
            docker --version || sudo docker --version
            mkdir -p devops

      - name: secure copy to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          source: docker-compose.yml
          target: ~/devops

      - name: ssh to run the container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          script: |
            echo "running the compose file...."
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            export DOCKER_TAG=${{ github.sha }}
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            cd ~/devops && docker compose down && docker compose up -d --build --force-recreate --pull always