name: Devsecops-pipeline
on:
  push:
    branches:
      [master]
  workflow_dispatch:

jobs:
  
    code-quality:
      uses: ./.github/workflows/code-quality-check.yml
    
    secret-scan:
      uses: ./.github/workflows/secret-scan.yml

    dependency-check:
      uses: ./.github/workflows/dependency-scan.yml

    docker-lint:
      uses: ./.github/workflows/docker-lint.yml

    docker-build-push:
      needs: [code-quality, secret-scan, dependency-check, docker-lint]
      uses: ./.github/workflows/docker-build-push.yml
      secrets: inherit

    docker-image-scan:
      needs: [docker-build-push]
      uses: ./.github/workflows/image-scan.yml
      secrets: inherit

    # docker-deploy-to-server:
    #   uses: ./.github/workflows/deploy-to-server.yml
    
