name: build and push docker image
on:
  workflow_dispatch:
jobs: 
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker build and push
        uses: docker/build-push-action@v6
        with:
         context: .
         push: true
         tags: ${{ vars.DOCKERHUB_USER }}/flask-app-image:latest