name: deploy code on self hosted runner in docker container
on: 
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
        env:
          DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
        steps:
          - name: code checkout
            uses: actions/checkout@4

          - name: deploy using docker compose file
            run: docker-compose up --build