name: docker image scan
on:
  workflow_call:

jobs:
  docker-image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkput code
        uses: actions/checkout@v4

      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Trivy Scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ vars.DOCKERHUB_USER }}/flask-app-image:latest
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          trivyignore: ${{ github.workspace }}/.trivyignore